### ISSUE TITLE
Neovim Syntax Highlighting

### ISSUE THREAD

**Issue by blytheaw** [dynamotn/tree-sitter-dbml#2]
Does this support syntax highlighting in Neovim using nvim-treesitter?

I have managed to install it through Neovim config, but appears to have no effect on a *.dbml file for me.

**Comment by dynamotn** [comment]
How did you setup this @blytheaw?
You should setup follow these codes:

```lua
local parser_config = require "nvim-treesitter.parsers".get_parser_configs()
parser_config.dbml = {
  install_info = {
    url = 'https://github.com/dynamotn/tree-sitter-dbml',
    branch = 'main',
    files = { 'src/parser.c' },
  },
  filetype = "dbml",
}
vim.filetype.add({
  pattern = {
    ['.*%.dbml'] = 'dbml',
  }
})
```
After that, start `nvim` and `:TSInstall dbml`.

**Comment by blytheaw** [comment]
@dynamotn I used this config, and run : TSInstall dbml. It shows successfully installed but when I restart nvim and open a *.dbml file, there is no syntax highlighting.
